# Generated by Django 3.1.7 on 2021-03-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funzioni_iot', '0003_giornalista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titoli2',
            options={},
        ),
        migrations.AlterModelManagers(
            name='titoli2',
            managers=[
            ],
        ),
    ]
