# Generated by Django 3.1.7 on 2021-03-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funzioni_iot', '0004_auto_20210306_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcli', models.CharField(max_length=20)),
                ('descli', models.CharField(max_length=60)),
                ('citcli', models.CharField(max_length=60)),
                ('capcli', models.CharField(max_length=60)),
            ],
        ),
    ]
