# Generated by Django 3.0.13 on 2021-03-01 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clienti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcli', models.CharField(max_length=250)),
                ('codslugcli', models.SlugField(max_length=250, unique_for_date='codpublishcli')),
                ('codbodycli', models.TextField()),
                ('codpublishcli', models.DateTimeField(default=django.utils.timezone.now)),
                ('codcreatedcli', models.DateTimeField(auto_now_add=True)),
                ('codupdatedcli', models.DateTimeField(auto_now=True)),
                ('codstatuscli', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('codauthorcli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_clienti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-codpublishcli',),
            },
        ),
    ]
