# Generated by Django 3.1.7 on 2021-03-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_clienti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titoli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codtit', models.CharField(max_length=250)),
                ('codslugtit', models.SlugField(max_length=250, unique_for_date='codcreatedtit')),
                ('codisintit', models.CharField(max_length=250)),
                ('codbodytit', models.TextField()),
                ('codcreatedtit', models.DateTimeField(auto_now_add=True)),
                ('codupdatedtit', models.DateTimeField(auto_now=True)),
                ('codmintit', models.FloatField()),
                ('codmaxtit', models.FloatField()),
            ],
            options={
                'ordering': ('-codcreatedtit',),
            },
        ),
    ]
