# Generated by Django 3.1.7 on 2021-03-04 06:00

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_titoli'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='titoli',
            managers=[
                ('codpublished', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='titoli',
            name='codpublishtit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
