# Generated by Django 3.1.7 on 2021-03-04 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20210304_0600'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='titoli',
            managers=[
                ('codobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='titoli',
            name='codauthortit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_titoli', to='auth.user'),
            preserve_default=False,
        ),
    ]
